### ISSUE TITLE
Headshot counter doesn't work

### ISSUE THREAD

**Issue by Marfeld** [partiusfabaa/cs2-ranks#15]
Headshot counter doesn't work  :(

<img width="398" alt="Screenshot 2023-12-26 105417" src="https://github.com/partiusfabaa/cs2-ranks/assets/154004296/2f989f47-ec29-4dc6-9d61-11e86a18ee41">
<img width="285" alt="Screenshot 2023-12-26 105535" src="https://github.com/partiusfabaa/cs2-ranks/assets/154004296/85091870-a5f1-425f-891d-e0fad08855f2">

And it only works once !top after every map change if there are a lot of players on it.
When I enter !top the second time after a few minutes nothing happens.

Best regards
Mario

**Comment by lostsoul6** [comment]
@Marfeld were you able to find a solution to it?

**Comment by Marfeld** [comment]
The counter has been working since the last update. But it only works if I don't have the headshot points set to 0 in the config. It would be good if the counter would still work. That was my last stand. 

What also causes problems is !top. If the server is pretty full of players then !top no longer works. When I'm alone, everything works great.

Greetings Mario

**Comment by Marfeld** [comment]
The only thing that doesn't work for me yet is "!Top". Always doesn't work when there are a lot of players on the server. Otherwise everything works.

**Comment by lostsoul6** [comment]
@Marfeld , were you able to find a way to solve this issue? I was in the server with 17 other players and !top didn't work . it seems when there are many players in the server , it doesn't work .

**Comment by Marfeld** [comment]
It's the same with me. I haven't found a solution yet, but I don't know much about it either. Hope it gets fixed.
