### ISSUE TITLE
plugin wont load [fixed]

### ISSUE THREAD

**Issue by y3request** [partiusfabaa/cs2-ranks#4]
I put the plugin in /game/csgo/addons/counterstrikesharp/plugins/Ranks

I restart server. No configs generated. 
I go in test with !ranks, nothing.
I try the console commands, unknown command.
It isn't loading for me.
I am on most recent counter-strikesharp

I have many other plugins working and running, connected to databases. Metamod and cssharp.

**Comment by partiusfabaa** [comment]
if they don't start, there must be some errors. If there are, send them to me

**Comment by y3request** [comment]
Sorry actually my mistake, trying again.
I thought I had newest version as I updated a bit over 24hrs ago. But I believe I was out of date.

Yeah it works now. So many updates lol
