### ISSUE TITLE
Fake Ranks issues

### ISSUE THREAD

**Issue by chycken** [partiusfabaa/cs2-ranks#44]
Hello @partiusfabaa  , in my server, everyone starts in silver 2 instead of silver 1.
My configs:
{
  "Type": 1,
  "FakeRank": {
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "10": 10,
    "11": 11,
    "12": 12,
    "13": 13,
    "14": 14,
    "15": 15,
    "16": 16,
    "17": 17,
    "18": 18
  }
}
"Ranks": {
    "Silver I": 0,
    "Silver II": 150,
    "Silver III": 300,
    "Silver IV": 600,
    "Silver Elite": 1000,
    "Silver Elite Master": 1400,
    "Gold Nova I": 1900,
    "Gold Nova II": 2400,
    "Gold Nova III": 2900,
    "Gold Nova Master": 3500,
    "Master Guardian I": 4000,
    "Master Guardian II": 4600,
    "Master Guardian Elite": 5200,
    "BigStar": 5900,
    "Legendary Eagle": 6600,
    "Legendary Eagle Master": 7500,
    "Supreme": 8300,
    "The Global Elite": 9000

Another thing: if I add xp to someone from console (for ex: 12000) then this player will be Global elite in top list, but this player's fakerank will be still silver or whatever it was because the plugin doesnt refresh the rank table in mysql..

**Comment by Letaryat** [comment]
There is something wrong with the fake rank module or fakeranks reveal all metamod plugin. Everyone gets +1 higher rank on scoreboard than it should be. I think there could be a problem with that it doesn't load the "None" rank on scoreboard but I might be wrong.
