### ISSUE TITLE
[Enhancement] Possible to expand the ranks + colors?

### ISSUE THREAD

**Issue by jinnsTaRR** [partiusfabaa/cs2-ranks#5]
1. It would be cool if you could expand the rankings yourself so that you could set more ranks for an extra long grind ( I know that you can increase the points yourself, but i want like 30 ranks :) )
2. that you can adjust the color for the respective ranks yourself

**Comment by partiusfabaa** [comment]
> 1. It would be cool if you could expand the rankings yourself so that you could set more ranks for an extra long grind ( I know that you can increase the points yourself, but i want like 30 ranks :) )
> 2. that you can adjust the color for the respective ranks yourself

I didn't quite get it, but you can add your own ranks. You can delete all of mine and put in your own. There's no problem with that. I'll think about the colors.
