### ISSUE TITLE
The database can no longer be edited.

### ISSUE THREAD

**Issue by Marfeld** [partiusfabaa/cs2-ranks#8]
The database can no longer be edited.
Can no longer delete or edit a player there.
Is it wanted like that?

<img width="728" alt="Screenshot 2023-12-16 162313" src="https://github.com/partiusfabaa/cs2-ranks/assets/154004296/dabc4a0b-e59e-480b-8d3f-d58a294af9fd">

**Comment by partiusfabaa** [comment]
> The database can no longer be edited. Can no longer delete or edit a player there. Is it wanted like that?
> 
> <img alt="Screenshot 2023-12-16 162313" width="728" src="https://private-user-images.githubusercontent.com/154004296/291000820-dabc4a0b-e59e-480b-8d3f-d58a294af9fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3Nzg5NzUsIm5iZiI6MTcwMjc3ODY3NSwicGF0aCI6Ii8xNTQwMDQyOTYvMjkxMDAwODIwLWRhYmM0YTBiLWU1OWUtNDgwYi04ZDNmLWQ1OGEyOTRhZjlmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwMjA0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODdmNjYzMGExNDNiZTBiNzI3YTJjMGQ4ZDIxZTk0ZDIxYmE2ZjczY2M4ZWVjNjc3NmI1MjU0NWRhMDBhMGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u72EIAYMWtfPLmYbNs0ALfvHDAfeJaObEqQqdwIihMU">

edit something only by SQL query

**Comment by Marfeld** [comment]
Yes, I always edited it there to set up and test the plugin. Or e.g. Individual players deleted if something wasn't right. The !lvl !2 Reset Player function doesn't work for me either.
